version: '3'

services:

 mongo:
  container_name: monodb
  image: mongo:latest
  restart: always
  ports:
  - 27017:27017
  environment:
   MONGO_INITDB_ROOT_USERNAME: admin
   MONGO_INITDB_ROOT_PASSWORD: admin

 mongo-express:
  image: mongo-express:latest
  restart: always
  ports:
  - 8081:8081
  environment:
   ME_CONFIG_MONGODB_ADMINUSERNAME: admin
   ME_CONFIG_MONGODB_ADMINPASSWORD: admin